#!/usr/bin/env tsx

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

// @ts-ignore ign
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

interface JsonSchemaProperty {
  type: string;
  const?: string;
  description?: string;
  properties?: Record<string, any>;
  required?: string[];
  additionalProperties?: boolean;
  $schema?: string;
}

interface SocketEvent {
  type: string;
  description?: string;
  properties: {
    event: JsonSchemaProperty;
    payload: JsonSchemaProperty;
  };
}

interface SocketSchema {
  $schema: string;
  title: string;
  description: string;
  type: string;
  properties: Record<string, SocketEvent>;
  definitions?: Record<string, any>;
}

const SCHEMA_URL = "http://localhost:3001/schema/socket.json";
const OUTPUT_DIR = join(__dirname, "../src/generated/socket");

async function fetchSchema(): Promise<SocketSchema> {
  console.log(`Fetching schema from ${SCHEMA_URL}...`);
  const response = await fetch(SCHEMA_URL);
  if (!response.ok) {
    throw new Error(`Failed to fetch schema: ${response.statusText}`);
  }
  return response.json();
}

function eventNameToTypeName(eventName: string): string {
  return eventName
    .split(/[:\-_]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function eventNameToZodName(eventName: string): string {
  const typeName = eventNameToTypeName(eventName);
  return `${typeName.charAt(0).toLowerCase()}${typeName.slice(1)}Schema`;
}

function jsonSchemaToZod(schema: any, indent = 0): string {
  const indentStr = "  ".repeat(indent);

  if (!schema || typeof schema !== "object") {
    return "z.unknown()";
  }

  // Handle anyOf (union types - typically nullable fields)
  if (schema.anyOf && Array.isArray(schema.anyOf)) {
    const types = schema.anyOf
      .map((s: any) => {
        if (s.type === "null") return ".nullable()";
        return null;
      })
      .filter(Boolean);

    // If it's a nullable pattern
    if (types.length > 0 && schema.anyOf.length === 2) {
      const nonNullSchema = schema.anyOf.find((s: any) => s.type !== "null");
      if (nonNullSchema) {
        return `${jsonSchemaToZod(nonNullSchema, indent)}.nullable()`;
      }
    }

    // General union
    const unionTypes = schema.anyOf.map((s: any) => jsonSchemaToZod(s, indent));
    return `z.union([${unionTypes.join(", ")}])`;
  }

  // Handle enum
  if (schema.enum && Array.isArray(schema.enum)) {
    const values = schema.enum.map((v: any) => JSON.stringify(v)).join(", ");
    return `z.enum([${values}])`;
  }

  // Handle const
  if (schema.const !== undefined) {
    return `z.literal(${JSON.stringify(schema.const)})`;
  }

  // Handle type
  switch (schema.type) {
    case "string":
      return "z.string()";

    case "number":
      return "z.number()";

    case "integer":
      return "z.number().int()";

    case "boolean":
      return "z.boolean()";

    case "null":
      return "z.null()";

    case "array":
      if (schema.items) {
        const itemSchema = jsonSchemaToZod(schema.items, indent);
        return `z.array(${itemSchema})`;
      }
      return "z.array(z.unknown())";

    case "object": {
      if (!schema.properties) {
        return "z.object({})";
      }

      const properties: string[] = [];
      for (const [key, value] of Object.entries(schema.properties)) {
        const propSchema = jsonSchemaToZod(value, indent + 1);
        const isRequired = schema.required?.includes(key);
        const optionalSuffix = isRequired ? "" : ".optional()";

        properties.push(
          `${indentStr}  ${key}: ${propSchema}${optionalSuffix},`
        );
      }

      let objectStr = `z.object({\n${properties.join("\n")}\n${indentStr}})`;

      // Handle additionalProperties
      if (schema.additionalProperties === false) {
        objectStr += ".strict()";
      }

      return objectStr;
    }

    default:
      return "z.unknown()";
  }
}

function generateZodSchemas(schema: SocketSchema): string {
  const lines: string[] = [
    "// Generated by scripts/generate-socket-types.ts",
    "// Do not edit this file manually",
    "",
    'import { z } from "zod";',
    "",
  ];

  const eventNames = Object.keys(schema.properties).sort();

  for (const eventName of eventNames) {
    const event = schema.properties[eventName];
    const payloadSchema = event.properties.payload;

    if (!payloadSchema) {
      console.warn(`⚠️  No payload schema for event: ${eventName}`);
      continue;
    }

    const zodName = eventNameToZodName(eventName);
    const typeName = eventNameToTypeName(eventName);

    try {
      const zodSchemaCode = jsonSchemaToZod(payloadSchema, 0);

      lines.push(`// Event: ${eventName}`);
      if (event.description) {
        lines.push(`// ${event.description}`);
      }
      lines.push(`export const ${zodName} = ${zodSchemaCode};`);
      lines.push("");
      lines.push(`export type ${typeName}Event = z.infer<typeof ${zodName}>;`);
      lines.push("");
    } catch (error) {
      console.error(`❌ Failed to generate schema for ${eventName}:`, error);
    }
  }

  return lines.join("\n");
}

function generateEventMap(schema: SocketSchema): string {
  const lines: string[] = [
    "// Generated by scripts/generate-socket-types.ts",
    "// Do not edit this file manually",
    "",
    "import type {",
  ];

  const eventNames = Object.keys(schema.properties).sort();

  for (const eventName of eventNames) {
    const typeName = eventNameToTypeName(eventName);
    lines.push(`  ${typeName}Event,`);
  }

  lines.push('} from "./events";');
  lines.push("");
  lines.push("/**");
  lines.push(" * Type-safe Socket.IO event map");
  lines.push(
    " * Use this to get proper typing for socket.on() and socket.emit()"
  );
  lines.push(" */");
  lines.push("export interface SocketEventMap {");

  for (const eventName of eventNames) {
    const typeName = eventNameToTypeName(eventName);
    lines.push(`  "${eventName}": ${typeName}Event;`);
  }

  lines.push("}");
  lines.push("");
  lines.push("export type SocketEventName = keyof SocketEventMap;");
  lines.push("");
  lines.push(
    "export type SocketEventPayload<T extends SocketEventName> = SocketEventMap[T];"
  );
  lines.push("");

  return lines.join("\n");
}

function generateIndex(schema: SocketSchema): string {
  const lines: string[] = [
    "// Generated by scripts/generate-socket-types.ts",
    "// Do not edit this file manually",
    "",
    "// Export all Zod schemas",
    'export * from "./events";',
    "",
    "// Export event map and types",
    'export type { SocketEventMap, SocketEventName, SocketEventPayload } from "./event-map";',
    "",
  ];

  return lines.join("\n");
}

async function main() {
  try {
    console.log("🚀 Starting Socket.IO type generation...\n");

    // Fetch schema
    const schema = await fetchSchema();
    console.log(
      `✅ Fetched schema with ${Object.keys(schema.properties).length} events\n`
    );

    // Create output directory
    mkdirSync(OUTPUT_DIR, { recursive: true });
    console.log(`📁 Created output directory: ${OUTPUT_DIR}\n`);

    // Generate files
    console.log("📝 Generating Zod schemas...");
    const eventsContent = generateZodSchemas(schema);
    writeFileSync(join(OUTPUT_DIR, "events.ts"), eventsContent);
    console.log("   ✅ events.ts");

    console.log("📝 Generating event map...");
    const eventMapContent = generateEventMap(schema);
    writeFileSync(join(OUTPUT_DIR, "event-map.ts"), eventMapContent);
    console.log("   ✅ event-map.ts");

    console.log("📝 Generating index...");
    const indexContent = generateIndex(schema);
    writeFileSync(join(OUTPUT_DIR, "index.ts"), indexContent);
    console.log("   ✅ index.ts");

    console.log("\n✨ Socket.IO types generated successfully!");
    console.log(`   Output: ${OUTPUT_DIR}`);
  } catch (error) {
    console.error("\n❌ Error generating Socket.IO types:", error);
    process.exit(1);
  }
}

main();
