// Re-export essential LiveKit client types that consumers might need
export {
  Room,
  Participant,
  LocalParticipant,
  RemoteParticipant,
  Track,
  LocalTrack,
  RemoteTrack,
  TrackPublication,
  LocalTrackPublication,
  RemoteTrackPublication,
  ConnectionQuality,
  ConnectionState,
  ParticipantEvent,
  RoomEvent,
  TrackEvent,
  DataPacket_Kind,
} from "livekit-client";

// Livekit hooks
export {
  usePagination,
  useParticipants,
  useRemoteParticipant,
  useRemoteParticipants,
  useConnectionQualityIndicator,
  useEnsureParticipant,
  useEnsureRoom,
  useLocalParticipant,
  useAudioPlayback,
  useConnectionState,
  useDataChannel,
  useDisconnectButton,
  useEnsureTrackRef,
  useIsMuted,
  useIsSpeaking,
  useIsRecording,
  useLiveKitRoom,
  useLocalParticipantPermissions,
  useMediaDevices,
  useParticipantInfo,
  useParticipantTracks,
  usePersistentUserChoices,
  usePinnedTracks,
  usePreviewTracks,
  useRoomContext,
  useRoomInfo,
  useSortedParticipants,
  useSpeakingParticipants,
  useStartAudio,
  useStartVideo,
  useSwipe,
  useTextStream,
  useTracks,
  useTrackByName,
  useTrackMutedIndicator,
  useTrackToggle,
  useTrackVolume,
} from "@livekit/components-react";

export {
  AudioTrack,
  LiveKitRoom,
  ParticipantContext,
  RoomAudioRenderer,
  RoomContext,
  StartAudio,
  StartMediaButton,
  VideoTrack,
} from "@livekit/components-react";
