trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - task: npmAuthenticate@0
    inputs:
      workingFile: .npmrc
    displayName: 'Authenticate to Azure Artifacts'

  - script: npm install -g pnpm
    displayName: 'Install pnpm'

  - script: pnpm install
    displayName: 'Install dependencies'

  - script: pnpm run build
    displayName: 'Build package'

  - script: pnpm publish-packages
    displayName: 'Publish package'
